data : "cifar100"
train_path  : "data/datasets/cifar100_train_all.pth"
test_path   : "data/datasets/cifar100_test_all.pth"
evaluate_robustness_path : "data/datasets/cifar100_subset_10_per_class.pth"
num_classes : 100
# Projected Gradient Descent (PGD)
adversarial_attack : "PGD"
epsilon : 0.03137
epsilon_test : 0.03137
alpha : 0.005
steps : 40
random_start : true
num_epochs : 200
lr : 0.001
batch_size : 128
n :
  - 3072
  - 20
  - 20
  - 100
K : 3
name_network : "fcna-cifar100"


  